version: '3.4'
services:
  webapi:
    image: exchange.rates.webapi
    build:
      context: .
      dockerfile: WebApi.PresentationLayer/Dockerfile
    ports:
      - "8000:80"
    environment:
      InternalSources: http://sourceA:80/api/v1/exchangerates,http://sourceB:80/api/v1/exchangerates
      ExternalSources: A,B
    depends_on:
      - sourceA
      - sourceB
    networks:
      - web
  sourceA:
    image: exchange.rates.source
    build:
      context: .
      dockerfile: ExchangeRatesSource.PresentationLayer/Dockerfile
    environment:
      ExchangeRateType: A
      ConnectionStrings__Db: User ID=root; Password=root; Host=dbA; Port=5432; Database=postgres;
      ConnectionStrings__Redis: redisA:6379
    depends_on:
      - dbA
      - redisA
      - migratorA
    networks:
      - networkA
      - web
  sourceB:
    image: exchange.rates.source
    build:
      context: .
      dockerfile: ExchangeRatesSource.PresentationLayer/Dockerfile
    environment:
      ExchangeRateType: B
      ConnectionStrings__Db: User ID=root; Password=root; Host=dbB; Port=5432; Database=postgres;
      ConnectionStrings__Redis: redisB:6379
    depends_on:
      - dbB
      - redisB
      - migratorB
    networks:
      - networkB
      - web
  dbA:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - networkA
  dbB:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - networkB
  redisA:
    image: redis:alpine
    networks:
      - networkA
  redisB:
    image: redis:alpine
    networks:
      - networkB
  migratorA:
    image: migrator
    build:
      context: .
      dockerfile: Migrator/Dockerfile
    environment:
      ConnectionStrings__Db: User ID=root; Password=root; Host=dbA; Port=5432; Database=postgres;
    depends_on:
      - dbA
    networks:
      - networkA
  migratorB:
    image: migrator
    build:
      context: .
      dockerfile: Migrator/Dockerfile
    environment:
      ConnectionStrings__Db: User ID=root; Password=root; Host=dbB; Port=5432; Database=postgres;
    depends_on:
      - dbB
    networks:
      - networkB
networks:
  networkB:
  networkA:
  web: