version: '3.4'
services:
  webapi:
    image: exchange.rates.webapi
    build:
      context: .
      dockerfile: WebApi.PresentationLayer/Dockerfile
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sourceA
  sourceA:
    image: exchange.rates.source.a
    build:
      context: .
      dockerfile: ExchangeRatesSource.PresentationLayer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ExchangeRateType: A
      ConnectionStrings__Db: User ID=root; Password=root; Host=dbA; Port=5432; Database=postgres;
    depends_on:
      - dbA
  sourceB:
    image: exchange.rates.source.b
    build:
      context: .
      dockerfile: ExchangeRatesSource.PresentationLayer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ExchangeRateType: B
      ConnectionStrings__Db: User ID=root; Password=root; Host=dbB; Port=5432; Database=postgres;
    depends_on:
      - dbB
  dbA:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8001:5432"
  dbB:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "8002:5432"
    
    
