version: '3.4'
services:
  webapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  sourceA:
    ports:
      - "8005:80"
  sourceB:
    ports:
      - "8006:80"
  dbA:
    ports:
      - "8001:5432"
  dbB:
    ports:
      - "8002:5432"
  redisA:
    ports:
      - "8003:6379"
  redisB:
    ports:
      - "8004:6379"