// <auto-generated />


#nullable disable

using System;
using ExchangeRatesSource.InfrastructureLayer;
using ExchangeRatesSource.InfrastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
namespace Migrator.Migrations
{
    [DbContext(typeof(ExchangeRateContext))]
    [Migration("20220428182040_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExchangeRatesSource.DomainLayer.ExchangeRateType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateOnly>("LastUpdateDate")
                        .HasColumnType("date");

                    b.HasKey("Name");

                    b.ToTable("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
